In [2]:
import numpy as np

In [3]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 6.,  3.,  8.,  6.],
       [ 1.,  9.,  6.,  9.],
       [ 1.,  4.,  3.,  8.]])

In [5]:
a.resize((2,6))
a

array([[ 6.,  3.,  8.,  6.,  1.,  9.],
       [ 6.,  9.,  1.,  4.,  3.,  8.]])

In [6]:
a.reshape(3,-1)

array([[ 6.,  3.,  8.,  6.],
       [ 1.,  9.,  6.,  9.],
       [ 1.,  4.,  3.,  8.]])

In [7]:
a = np.floor(10*np.random.random((2,2)))
a

array([[ 0.,  8.],
       [ 3.,  9.]])

In [8]:
b = np.floor(10*np.random.random((2,2)))
b

array([[ 8.,  7.],
       [ 9.,  6.]])

In [9]:
np.vstack((a,b))

array([[ 0.,  8.],
       [ 3.,  9.],
       [ 8.,  7.],
       [ 9.,  6.]])

In [18]:
 np.hstack((a,b))

array([ 4.,  2.,  2.,  8.])

In [19]:
from numpy import newaxis
np.column_stack((a,b))   # With 2D arrays 

array([[ 4.,  2.],
       [ 2.,  8.]])

In [20]:
a = np.array([4.,2.])
b = np.array([2.,8.])
a[:,newaxis]  # This allows to have a 2D columns vector

array([[ 4.],
       [ 2.]])

In [21]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [14]:
np.vstack((a[:,newaxis],b[:,newaxis])) # The behavior of vstack is different

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

In [22]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [24]:
a = np.floor(10*np.random.random((2,12)))
a

array([[ 3.,  6.,  0.,  8.,  9.,  7.,  0.,  5.,  2.,  1.,  3.,  5.],
       [ 9.,  9.,  0.,  7.,  1.,  5.,  6.,  6.,  3.,  5.,  4.,  6.]])

In [25]:
np.hsplit(a,3)   # Split a into 3

[array([[ 3.,  6.,  0.,  8.],
        [ 9.,  9.,  0.,  7.]]), array([[ 9.,  7.,  0.,  5.],
        [ 1.,  5.,  6.,  6.]]), array([[ 2.,  1.,  3.,  5.],
        [ 3.,  5.,  4.,  6.]])]

In [29]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[ 3.,  6.,  0.,  8.],
        [ 9.,  9.,  0.,  7.]]),
 array([[ 9.,  7.,  0.,  5.,  2.,  1.,  3.,  5.],
        [ 1.,  5.,  6.,  6.,  3.,  5.,  4.,  6.]])]

In [30]:
np.hsplit(a,(3,))  

[array([[ 3.,  6.,  0.],
        [ 9.,  9.,  0.]]),
 array([[ 8.,  9.,  7.,  0.,  5.,  2.,  1.,  3.,  5.],
        [ 7.,  1.,  5.,  6.,  6.,  3.,  5.,  4.,  6.]])]

In [31]:
np.vsplit(a,(1,))  

[array([[ 3.,  6.,  0.,  8.,  9.,  7.,  0.,  5.,  2.,  1.,  3.,  5.]]),
 array([[ 9.,  9.,  0.,  7.,  1.,  5.,  6.,  6.,  3.,  5.,  4.,  6.]])]

In [32]:
a = np.arange(12)
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

In [33]:
b.shape = 3,4    # changes the shape of a
a.shape

(3, 4)

In [36]:
def f(x):
     print(id(x))  
        
id(a) 

80362352

In [37]:
f(a)

80362352


In [38]:
c = a.view()
c is a

False

In [39]:
c.base is a

True

In [41]:
c.flags.owndata

False

In [46]:
a.flags.owndata

True

In [42]:
c.shape = 2,6

In [43]:
a.shape

(3, 4)

In [44]:
c[0,4] = 1234

In [45]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [47]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [48]:
d = a.copy()                          # a new array object with new data is created
d is a

False

In [49]:
d.base is a 

False

In [50]:
d[0,0] = 9999

In [51]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])