In [4]:
import numpy as np
from numpy import pi

In [13]:
a = np.ones(3, dtype=np.int32)
a

array([1, 1, 1])

In [15]:
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [7]:
c = a+b
c

array([ 1.        ,  2.57079633,  4.14159265])

In [8]:
c.dtype.name

'float64'

In [10]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [11]:
d.dtype.name

'complex128'

In [16]:
a = np.random.random((2,3))
a

array([[ 0.43457161,  0.98497115,  0.17324304],
       [ 0.19255207,  0.76246235,  0.91415693]])

In [17]:
a.sum()

3.4619571497630042

In [18]:
a.min()

0.17324303771814076

In [19]:
a.max()

0.98497114684664921

In [24]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
b.sum(axis=0) 

array([12, 15, 18, 21])

In [25]:
b.sum(axis=1)

array([ 6, 22, 38])

In [26]:
b.sum()

66

In [22]:
b.min(axis=1)

array([0, 4, 8])

In [23]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [28]:
?b.cumsum(axis=1)

In [30]:
B = np.arange(3)
B

array([0, 1, 2])

In [35]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [32]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [34]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([ 2.,  0.,  6.])

In [36]:
D = np.array([2., -1., 4.,0])
np.add(B, D)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [38]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [39]:
a[2]

8

In [40]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [41]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000

In [42]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729], dtype=int32)

In [43]:
a[ : :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000], dtype=int32)

In [44]:
for i in a:
     print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: invalid value encountered in power
  from ipykernel import kernelapp as app


In [50]:
(-1000)**(1/3.)

(5+8.660254037844384j)

In [51]:
1000**(1/3.)

9.999999999999998

In [52]:
def f(x,y):
    return 10*x+y

In [53]:
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [54]:
b[2,3]

23

In [59]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [60]:
b[ : ,1]

array([ 1, 11, 21, 31, 41])

In [62]:
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [58]:
?np.fromfunction

In [63]:
b[-1]

array([40, 41, 42, 43])

In [64]:
c = np.array( [[[  0,  1,  2],
                [ 10, 12, 13]],
              [[100,101,102],
                [110,112,113]]])

In [65]:
c.shape

(2, 2, 3)

In [66]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [67]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [68]:
for row in b:
     print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [69]:
for element in b.flat:
     print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [71]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 9.,  2.,  5.,  0.],
       [ 8.,  2.,  3.,  7.],
       [ 2.,  5.,  0.,  4.]])

In [74]:
?np.floor()

In [75]:
num = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

In [77]:
np.floor(num)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [78]:
a.ravel()

array([ 9.,  2.,  5.,  0.,  8.,  2.,  3.,  7.,  2.,  5.,  0.,  4.])

In [79]:
a

array([[ 9.,  2.,  5.,  0.],
       [ 8.,  2.,  3.,  7.],
       [ 2.,  5.,  0.,  4.]])

In [80]:
a.reshape(6,2)

array([[ 9.,  2.],
       [ 5.,  0.],
       [ 8.,  2.],
       [ 3.,  7.],
       [ 2.,  5.],
       [ 0.,  4.]])

In [81]:
a.T

array([[ 9.,  8.,  2.],
       [ 2.,  2.,  5.],
       [ 5.,  3.,  0.],
       [ 0.,  7.,  4.]])

In [82]:
a.T.shape

(4, 3)

In [83]:
a.shape

(3, 4)