In [4]:
import numpy as np

a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121], dtype=int32)

In [5]:
i = np.array( [ 1,1,3,8,5 ] )
i

array([1, 1, 3, 8, 5])

In [6]:
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [7]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )
a[j]  

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [8]:
palette = np.array( [ [0,0,0],                # 黑色
                      [255,0,0],              # 红色
                      [0,255,0],              # 绿色
                      [0,0,255],              # 蓝色
                      [255,255,255] ] )       # 白色

In [9]:
image = np.array( [ [ 0, 1, 2, 0 ],           
                    [ 0, 3, 4, 0 ]  ] )

In [11]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [13]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
i = np.array( [ [0,1],
                 [1,2] ] )
i

array([[0, 1],
       [1, 2]])

In [17]:
j = np.array( [ [2,1], 
                [3,3] ] )
j

array([[2, 1],
       [3, 3]])

In [18]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [19]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [20]:
a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [22]:
l = [i,j]
l

[array([[0, 1],
        [1, 2]]), array([[2, 1],
        [3, 3]])]

In [23]:
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [25]:
s = np.array( [i,j] )
a[s] 

IndexError: index 3 is out of bounds for axis 0 with size 3

In [26]:
a[tuple(s)] 

array([[ 2,  5],
       [ 7, 11]])

In [27]:
time = np.linspace(20, 145, 5)
time

array([  20.  ,   51.25,   82.5 ,  113.75,  145.  ])

In [28]:
data = np.sin(np.arange(20)).reshape(5,4)
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [29]:
ind = data.argmax(axis=0)
ind

array([2, 0, 3, 1], dtype=int64)

In [30]:
ind = data.argmax(axis=1)
ind

array([2, 3, 0, 2, 3], dtype=int64)

In [32]:
time_max = time[ind]
time_max

array([  82.5 ,  113.75,   20.  ,   82.5 ,  113.75])

In [39]:
data_max = data[ind]
data_max

array([[ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [40]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [42]:
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

In [43]:
a = np.arange(5)
a[[0,0,2]]=[1,2,3]
a

array([2, 1, 3, 3, 4])

In [44]:
a = np.arange(5)
a[[0,0,2]]+=1
a

array([1, 1, 3, 3, 4])

In [47]:
a = np.arange(12).reshape(3,4)
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [48]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [49]:
a[b] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [56]:
import numpy as np
import matplotlib.pyplot as plt

def mandelbrot(h,w,maxit=20):
    """Returns an image of the Mandelbrot fractal of size (h,w)."""
    y,x = np.ogrid[-1.4:1.4:h*1j,-2:0.8:w*1j]
    c = x+y*1j
    z = c
    divtime = maxit + np.zeros(z.shape, dtype=int)

    for i in range(maxit):
        z = z**2 + c
        diverge = z*np.conj(z) > 2**2            # who is diverging
        div_now = diverge & (divtime==maxit)  # who is diverging now
        divtime[div_now] = i                  # note when
        z[diverge] = 2                        # avoid diverging too much

    return divtime
plt.imshow(mandelbrot(400,400))
plt.show()

In [5]:
a = np.arange(12).reshape(3,4)
b1 = np.array([False,True,True])  
b2 = np.array([True,False,True,False])

In [6]:
a[b1,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a[b1]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a[:,b2] 

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [12]:
a[b1,b2] 

array([ 4, 10])